### ISSUE TITLE
测试阿里云服务器，填入token,以及硬盘ID 提示Api验证失败

### ISSUE THREAD

**Issue by chaodada** [aoaostar/aliyundrive_uploader_for_baota#1]

**Comment by aoaostar** [comment]
首次运行得先生成config.json文件，插件没有自动生成，已经ok了

**Comment by chaodada** [comment]
谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月29日(星期四) 晚上7:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aoaostar/aliyundrive_uploader_for_baota] 测试阿里云服务器，填入token,以及硬盘ID 提示Api验证失败 (#1)





 
OK了，首次运行得先生成config.json文件，插件没有自动生成，已经ok了
