### ISSUE TITLE
为什么更新之后好多功能都没有了呢？

### ISSUE THREAD

**Issue by xiaocainiao2020** [aoaostar/aliyundrive_uploader_for_baota#10]
比如以前可以看到已完成的和失败的，还能看到上传的进度百分比，现在怎么都没有了呢？

**Comment by aoaostar** [comment]
已完成的和失败的完全可以通过日志来查看
上传进度百分比在终端有显示
插件只是显示了日志

**Comment by xiaocainiao2020** [comment]
> 已完成的和失败的完全可以通过日志来查看 上传进度百分比在终端有显示 插件只是显示了日志

那使用宝塔插件版本的话怎么样从终端查看进度呢？

**Comment by aoaostar** [comment]
> > 已完成的和失败的完全可以通过日志来查看 上传进度百分比在终端有显示 插件只是显示了日志
> 
> 那使用宝塔插件版本的话怎么样从终端查看进度呢？

目前是不行的

**Comment by aoaostar** [comment]
https://github.com/aoaostar/alidrive-uploader/commit/a4bb7d96264139a5102a99389169558a392891df

![image](https://user-images.githubusercontent.com/86001674/166703946-b9ba193d-e0df-4af7-97ad-e89c1f34f678.png)
