### ISSUE TITLE
上传中途失败

### ISSUE THREAD

**Issue by xiaocainiao2020** [aoaostar/aliyundrive_uploader_for_baota#11]
没升级之前用老版本可以上传的，升级了新版本之后，刚点了上传是一直在上传的，过了段时间我再去看就失败了。视频文件大概15个G，用的阿里云上海的轻量8M宽带。
![image](https://user-images.githubusercontent.com/61716543/166160366-38545b21-f8ce-428e-9061-be6e050caa80.png)

**Comment by aoaostar** [comment]
相似问题：https://github.com/aoaostar/alidrive-uploader/issues/55
