### ISSUE TITLE
能不能加个定时任务，或者提供shell指定目录上传的命令

### ISSUE THREAD

**Issue by imchuyun** [aoaostar/aliyundrive_uploader_for_baota#17]
能不能加个定时任务，或者提供shell指定目录上传的命令。
使用阿里云盘自动备份网站

**Comment by aoaostar** [comment]
你定时执行上传宝塔备份目录就能实现备份网站这个功能啊
没有必要另外加啊

**Comment by imchuyun** [comment]
感谢您对冷心网络的支持您发送的邮件我们已经收到了，我们在线就会回复您的哦！不担心任何问题，只要有耐心！~by.冷心团队
