### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by huoshen80** [aoaostar/aliyundrive_uploader_for_baota#19]
好像寄了，一打开就报错

**Comment by aoaostar** [comment]
出错图

**Comment by huoshen80** [comment]
![IMG_20220721_113707.jpg](https://user-images.githubusercontent.com/61808984/180124756-c87b3876-519c-40a0-be54-d6c363ff0705.jpg)
截图截不全，复制也不好复制，很快就没了那个窗口

**Comment by aoaostar** [comment]
> ![IMG_20220721_113707.jpg](https://user-images.githubusercontent.com/61808984/180124756-c87b3876-519c-40a0-be54-d6c363ff0705.jpg) 截图截不全，复制也不好复制，很快就没了那个窗口

这个是因为你机器无法访问github api，所以请求超时了  
无伤大雅，其他功能应该是能用的

**Comment by huoshen80** [comment]
我没找到登录的入口感觉没法正常使用

**Comment by aoaostar** [comment]
> 我没找到登录的入口感觉没法正常使用

额，本插件没有登录

**Comment by huoshen80** [comment]
不能登陆怎么上传文件？em我不能理解

**Comment by aoaostar** [comment]
使用说明https://github.com/aoaostar/alidrive-uploader

**Comment by huoshen80** [comment]
你发的不是宝塔插件的教程吧，我没找到教程所说的的config.json。

**Comment by aoaostar** [comment]
举一反三，宝塔插件已经可视化了，直接在配置栏里填写

**Comment by huoshen80** [comment]
![image](https://user-images.githubusercontent.com/61808984/180431296-12d07b97-fbea-419d-85f1-17ae4fe27a99.png)
直接把配置文件的内容往这边填么？

**Comment by aoaostar** [comment]
> ![image](https://user-images.githubusercontent.com/61808984/180431296-12d07b97-fbea-419d-85f1-17ae4fe27a99.png) 直接把配置文件的内容往这边填么？

是的

**Comment by huoshen80** [comment]
![image](https://user-images.githubusercontent.com/61808984/180588489-fe80c4cd-9d2d-4315-bac1-ee851a43ed55.png)
这样填写后还是无法使用，服务器是国内的。

**Comment by aoaostar** [comment]
还要启动才行。。。
启动之后，在查看文件里选择上传文件

**Comment by huoshen80** [comment]
已经是启动了的，而且我点完保存，选别的界面回来这个配置界面里面的东西会消失，离大谱

**Comment by aoaostar** [comment]
。。。。
是没加载出来吧，消失倒不至于

**Comment by aoaostar** [comment]
config.json在插件目录下的core目录

**Comment by huoshen80** [comment]
没有core这个目录，还有真的消失，并不是没加载出来

**Comment by huoshen80** [comment]
![Screenshot_2022-07-23-11-56-11-01_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/61808984/180589608-2d17fde7-ecdc-4615-a356-5f7e5abcccc4.jpg)
请看截图确实没有core这个文件夹

**Comment by aoaostar** [comment]
哦哦，安装没有成功啊，重新安装一下吧

**Comment by huoshen80** [comment]
我使用了那个脚本，但是它报错，我的系统是Ubuntu22.04是不是没法安装这个插件？
我看你那边只有centos和debian的

**Comment by aoaostar** [comment]
给一下图
ubuntu是基于debian的

**Comment by huoshen80** [comment]
![image](https://user-images.githubusercontent.com/61808984/180601315-b96b41c9-e533-46eb-9cd4-e5362901bd36.png)
如图直接报错

**Comment by aoaostar** [comment]
> ![image](https://user-images.githubusercontent.com/61808984/180601315-b96b41c9-e533-46eb-9cd4-e5362901bd36.png) 如图直接报错

命令有误
```
bash install.sh install
```

**Comment by huoshen80** [comment]
![image](https://user-images.githubusercontent.com/61808984/180601619-a29cde4d-4003-4828-a549-8f141ccd8e80.png)
应该是可以了

**Comment by huoshen80** [comment]
但是这下载速度也太感人了吧

**Comment by aoaostar** [comment]
cf worker代理给墙了，速度实在慢的话，可以手动下载上传
alidrive-uploader仓库里releases处下载最新版本
然后上传到插件目录下的core目录即可
