### ISSUE TITLE
如果不后台常驻运行,会开启失败

### ISSUE THREAD

**Issue by mayishidai** [aoaostar/aliyundrive_uploader_for_baota#2]
如果不后台常驻运行,会开启失败,开启常驻运行就没有任何问题

日志是:

该文件夹不存在：D:\Pictures\，请重试
=================================================
        阿里云盘上传工具启动成功
        当前时间：2021-08-17 23:41:31
		REFRESH_TOKEN：人工隐藏
		DRIVE_ID：人工隐藏
		ROOT_PATH：云服务器备份/腾讯云/
		FILE_PATH：
		MULTITHREADING：True
		MAX_WORKERS：5
		CHUNK_SIZE：104857600
		RESUME：True
		OVERWRITE：True
		RETRY：3
		RESIDENT：False
		VERSIONS：v2021.0804.1200
=================================================

该文件夹不存在：D:\Pictures\，请重试
=================================================
        阿里云盘上传工具启动成功
        当前时间：2021-08-17 23:45:56
		REFRESH_TOKEN：人工隐藏
		DRIVE_ID：人工隐藏
		ROOT_PATH：云服务器备份/腾讯云/
		FILE_PATH：
		MULTITHREADING：True
		MAX_WORKERS：5
		CHUNK_SIZE：104857600
		RESUME：True
		OVERWRITE：True
		RETRY：3
		RESIDENT：False
		VERSIONS：v2021.0804.1200
=================================================

=================================================
        阿里云盘上传工具启动成功
        当前时间：2021-08-17 23:47:22
		REFRESH_TOKEN：人工隐藏
		DRIVE_ID：人工隐藏
		ROOT_PATH：云服务器备份/腾讯云/
		FILE_PATH：
		MULTITHREADING：True
		MAX_WORKERS：5
		CHUNK_SIZE：104857600
		RESUME：True
		OVERWRITE：True
		RETRY：3
		RESIDENT：True
		VERSIONS：v2021.0804.1200
=================================================

【shadowsocks_r_qr.png】正在校检文件中，耗时与文件大小有关
=================================================
        文件名：shadowsocks_r_qr.png
        hash：07af316b0dd2c50f9715454489859f266ba3fd8c
        文件大小：558
        文件路径：/www/vpn/shadowsocks_r_qr.png
=================================================

检索目录中
AccessToken已失效，尝试刷新AccessToken中
AccessToken刷新成功，准备返回
目录id获取成功611bda0fa7c771012aa74daea27080881f082995
正在上传【shadowsocks_r_qr.png】100.00%
【shadowsocks_r_qr.png】上传成功！消耗17秒
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中
当前无任务，等待新的任务队列中

**Comment by aoaostar** [comment]
你关闭常驻运行时是传了参数吗，config.json怎么填的

**Comment by mayishidai** [comment]
![image](https://user-images.githubusercontent.com/20534392/129761051-ebfdb54f-6cf7-4b89-b938-5c3d672190ab.png)
我是在这个面板上填的

**Comment by mayishidai** [comment]
我看到这个文件有这个东西
![image](https://user-images.githubusercontent.com/20534392/129761477-49ea33c5-2675-4709-84bc-26bcc817a0cc.png)
![image](https://user-images.githubusercontent.com/20534392/129761610-375c73de-19a3-4060-8657-0f331d46a529.png)

**Comment by mayishidai** [comment]
这个并没有暴露到面板上,请问我应该填什么呢

**Comment by aoaostar** [comment]
使用插件就必须使用常驻运行，没有使用了常驻运行，每次启动都会扫描FILE_PATH，然后提交上传任务到数据库，直到任务清空然后退出，使用常驻运行则不会扫描文件，只会从数据库查询任务，你为啥管着常驻运行呢？我不是写了宝塔插件需要开启常驻运行了吗？
