### ISSUE TITLE
请问一下这个上传失败是什么原因呢。

### ISSUE THREAD

**Issue by crll** [aoaostar/aliyundrive_uploader_for_baota#21]
`请问一下这个上传失败是什么原因呢。
![](https://m.360buyimg.com/babel/jfs/t1/113497/11/33329/3760/63dbb8a5F4b6cc3c7/082edf27573c7968.png)
![](https://m.360buyimg.com/babel/jfs/t1/215267/33/25139/62659/63dbb8a5F48d65fe1/a2fc333827d5f718.png)

**Comment by aoaostar** [comment]
drive id填错了

**Comment by crll** [comment]
确实是的，我重新登录一下，再获取就可以了。 感谢~
