### ISSUE TITLE
建议集成到宝塔的软件商店里面 方便更多人使用

### ISSUE THREAD

**Issue by chainofhonor** [aoaostar/aliyundrive_uploader_for_baota#3]
RT
甚至还可以设置收费模式  

另外希望增加一个功能,加密保存 

现在网盘都是全明文存储,根本不敢保存自己的照片等隐私信息

**Comment by aoaostar** [comment]
集成到宝塔的软件商店里面需要企业认证，我没有
加密保存可以自己加密后上传

**Comment by dreampen123** [comment]
可以试试淘宝，貌似可以办理企业认证，这个插件市场估计挺大。
