### ISSUE TITLE
为什么不显示我想要上传的文件夹呢？

### ISSUE THREAD

**Issue by xiaocainiao2020** [aoaostar/aliyundrive_uploader_for_baota#4]

**Comment by aoaostar** [comment]
你想多了，哪有

**Comment by xiaocainiao2020** [comment]
> 你想多了，哪有

是真的没显示，我把那个文件夹的里的文件移动到外面以后才看到那个文件的。

**Comment by xiaocainiao2020** [comment]
> 你想多了，哪有

![image](https://user-images.githubusercontent.com/61716543/134656707-b0891171-5033-41dd-b32a-123a22bdba3b.png)
如图，我这个文件夹里边有六个，但是只显示出来了四个。我要上传的那个文件夹没显示出来。

**Comment by aoaostar** [comment]
应该是没问题了
